### PR TITLE
fix: consolidate HTTPScaledObject status updates to prevent conflicts

### LINKED ISSUE #1402: ERROR    failed to update status on HTTPScaledObject
### Report

in our test setup we get a lot of error messages from the keda-add-ons-http-operator

### Expected Behavior

the operator should run without errors

### Actual Behavior

the operator complains about 

### Steps to Reproduce the Problem

1. install the http-add-on
2. create a HTTPScaledObject
3. view logs

### Logs from KEDA HTTP operator

```
kube-rbac-proxy I1204 23:20:55.564753       1 main.go:186] Valid token audiences: 
kube-rbac-proxy I1204 23:20:55.564834       1 main.go:316] Generating self signed cert as no cert is provided
kube-rbac-proxy I1204 23:20:57.036505       1 main.go:366] Starting TCP socket on 0.0.0.0:8443
kube-rbac-proxy I1204 23:20:57.037001       1 main.go:373] Listening securely on 0.0.0.0:8443
keda-add-ons-http-operator 2025-12-04T23:20:58Z    INFO    setup    starting manager
keda-add-ons-http-operator 2025-12-04T23:20:58Z    INFO    controller-runtime.metrics    Starting metrics server
keda-add-ons-http-operator 2025-12-04T23:20:58Z    INFO    controller-runtime.metrics    Serving metrics server    {"bindAddress": "127.0.0.1:8080", "secure": false}
keda-add-ons-http-operator 2025-12-04T23:20:58Z    INFO    starting server    {"name": "health probe", "addr": "[::]:8081"}
keda-add-ons-http-operator I1204 23:20:58.989979       1 leaderelection.go:254] attempting to acquire leader lease keda/http-add-on.keda.sh...
keda-add-ons-http-operator I1204 23:20:59.010097       1 leaderelection.go:268] successfully acquired lease keda/http-add-on.keda.sh
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Starting EventSource    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "source": "kind source: *v1alpha1.HTTPScaledObject"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Starting EventSource    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "source": "kind source: *v1alpha1.ScaledObject"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Starting Controller    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Starting workers    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "worker count": 1}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Reconciliation start    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Reconciling HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "Namespace": "wp-bedrock-sample", "DeploymentName": "wp-bedrock-sample-wordpress-bedrock"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Creating scaled objects    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "reconciler.appObjects": "addObjects", "HTTPScaledObject.name": "wp-bedrock-sample-wordpress-bedrock", "HTTPScaledObject.namespace": "wp-bedrock-sample", "external scaler host name": "keda-add-ons-http-external-scaler.keda:9090"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Creating App ScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "reconciler.appObjects": "addObjects", "HTTPScaledObject.name": "wp-bedrock-sample-wordpress-bedrock", "HTTPScaledObject.namespace": "wp-bedrock-sample", "ScaledObject": {"kind":"ScaledObject","apiVersion":"keda.sh/v1alpha1","metadata":{"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample","creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"wp-bedrock-sample","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"wordpress-bedrock","app.kubernetes.io/version":"1.0","helm.sh/chart":"wordpress-bedrock-0.1.141"},"annotations":{"meta.helm.sh/release-name":"wp-bedrock-sample","meta.helm.sh/release-namespace":"wp-bedrock-sample"},"ownerReferences":[{"apiVersion":"http.keda.sh/v1alpha1","kind":"HTTPScaledObject","name":"wp-bedrock-sample-wordpress-bedrock","uid":"b3551d95-4d76-487e-8301-4d8ac5514e9e","controller":true,"blockOwnerDeletion":true}]},"spec":{"scaleTargetRef":{"name":"wp-bedrock-sample-wordpress-bedrock-worker","apiVersion":"apps/v1","kind":"Deployment"},"pollingInterval":15,"cooldownPeriod":3600,"minReplicaCount":0,"maxReplicaCount":10,"advanced":{"restoreToOriginalReplicaCount":true,"scalingModifiers":{}},"triggers":[{"type":"external-push","metadata":{"httpScaledObject":"wp-bedrock-sample-wordpress-bedrock","scalerAddress":"keda-add-ons-http-external-scaler.keda:9090"}}]},"status":{}}}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Updating status on HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "resource version": "1483415071"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Updated status on HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "resource version": "1484873200"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Updating status on HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "resource version": "1484873200"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Updated status on HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "resource version": "1484873201"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Reconcile success    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "fe6985b4-aef7-4d8b-908a-dd6f86693729", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Reconciliation start    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Reconciling HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "Namespace": "wp-bedrock-sample", "DeploymentName": "wp-bedrock-sample-wordpress-bedrock"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Creating scaled objects    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "reconciler.appObjects": "addObjects", "HTTPScaledObject.name": "wp-bedrock-sample-wordpress-bedrock", "HTTPScaledObject.namespace": "wp-bedrock-sample", "external scaler host name": "keda-add-ons-http-external-scaler.keda:9090"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Creating App ScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "reconciler.appObjects": "addObjects", "HTTPScaledObject.name": "wp-bedrock-sample-wordpress-bedrock", "HTTPScaledObject.namespace": "wp-bedrock-sample", "ScaledObject": {"kind":"ScaledObject","apiVersion":"keda.sh/v1alpha1","metadata":{"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample","creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"wp-bedrock-sample","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"wordpress-bedrock","app.kubernetes.io/version":"1.0","helm.sh/chart":"wordpress-bedrock-0.1.141"},"annotations":{"meta.helm.sh/release-name":"wp-bedrock-sample","meta.helm.sh/release-namespace":"wp-bedrock-sample"},"ownerReferences":[{"apiVersion":"http.keda.sh/v1alpha1","kind":"HTTPScaledObject","name":"wp-bedrock-sample-wordpress-bedrock","uid":"b3551d95-4d76-487e-8301-4d8ac5514e9e","controller":true,"blockOwnerDeletion":true}]},"spec":{"scaleTargetRef":{"name":"wp-bedrock-sample-wordpress-bedrock-worker","apiVersion":"apps/v1","kind":"Deployment"},"pollingInterval":15,"cooldownPeriod":3600,"minReplicaCount":0,"maxReplicaCount":10,"advanced":{"restoreToOriginalReplicaCount":true,"scalingModifiers":{}},"triggers":[{"type":"external-push","metadata":{"httpScaledObject":"wp-bedrock-sample-wordpress-bedrock","scalerAddress":"keda-add-ons-http-external-scaler.keda:9090"}}]},"status":{}}}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Updating status on HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "resource version": "1484873200"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    ERROR    failed to update status on HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "httpso": {"apiVersion": "http.keda.sh/v1alpha1", "kind": "HTTPScaledObject", "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock"}, "error": "Operation cannot be fulfilled on httpscaledobjects.http.keda.sh \"wp-bedrock-sample-wordpress-bedrock\": the object has been modified; please apply your changes to the latest version and try again"}
keda-add-ons-http-operator github.com/kedacore/http-add-on/operator/controllers/http.SaveStatus
keda-add-ons-http-operator     github.com/kedacore/http-add-on/operator/controllers/http/condition_provider.go:26
keda-add-ons-http-operator github.com/kedacore/http-add-on/operator/controllers/http.(*HTTPScaledObjectReconciler).createOrUpdateApplicationResources
keda-add-ons-http-operator     github.com/kedacore/http-add-on/operator/controllers/http/app.go:71
keda-add-ons-http-operator github.com/kedacore/http-add-on/operator/controllers/http.(*HTTPScaledObjectReconciler).Reconcile
keda-add-ons-http-operator     github.com/kedacore/http-add-on/operator/controllers/http/httpscaledobject_controller.go:112
keda-add-ons-http-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
keda-add-ons-http-operator     sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:116
keda-add-ons-http-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
keda-add-ons-http-operator     sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:303
keda-add-ons-http-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
keda-add-ons-http-operator     sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263
keda-add-ons-http-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
keda-add-ons-http-operator     sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Updating status on HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "resource version": "1484873200"}
keda-add-ons-http-operator 2025-12-04T23:20:59Z    ERROR    failed to update status on HTTPScaledObject    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "httpso": {"apiVersion": "http.keda.sh/v1alpha1", "kind": "HTTPScaledObject", "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock"}, "error": "Operation cannot be fulfilled on httpscaledobjects.http.keda.sh \"wp-bedrock-sample-wordpress-bedrock\": the object has been modified; please apply your changes to the latest version and try again"}
keda-add-ons-http-operator github.com/kedacore/http-add-on/operator/controllers/http.SaveStatus
keda-add-ons-http-operator     github.com/kedacore/http-add-on/operator/controllers/http/condition_provider.go:26
keda-add-ons-http-operator github.com/kedacore/http-add-on/operator/controllers/http.(*HTTPScaledObjectReconciler).Reconcile
keda-add-ons-http-operator     github.com/kedacore/http-add-on/operator/controllers/http/httpscaledobject_controller.go:124
keda-add-ons-http-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
keda-add-ons-http-operator     sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:116
keda-add-ons-http-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
keda-add-ons-http-operator     sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:303
keda-add-ons-http-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
keda-add-ons-http-operator     sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263
keda-add-ons-http-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
keda-add-ons-http-operator     sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224
keda-add-ons-http-operator 2025-12-04T23:20:59Z    INFO    Reconcile success    {"controller": "httpscaledobject", "controllerGroup": "http.keda.sh", "controllerKind": "HTTPScaledObject", "HTTPScaledObject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}, "namespace": "wp-bedrock-sample", "name": "wp-bedrock-sample-wordpress-bedrock", "reconcileID": "84ecd32b-5178-4268-a98d-ae6e38373ffa", "httpscaledobject": {"name":"wp-bedrock-sample-wordpress-bedrock","namespace":"wp-bedrock-sample"}}

```

### HTTP Add-on Version

0.11.0

### Kubernetes Version

1.33

### Platform

Amazon Web Services

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Fedosin**
Refactor status update logic to ensure only one `SaveStatus` call per reconciliation. Previously, two consecutive `SaveStatus` calls caused conflicts as the first update changed the resource version.

Changes:
- Move status updates from `app.go` to `httpscaledobject_controller.go`
- Set `ConditionFalse` on error, `ConditionTrue` on success
- Simplify `app.go` to only handle resource creation/deletion

Fixes #1402

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Any necessary documentation is added, such as:
  - [`README.md`](../README.md)
  - [The `docs/` directory](../docs)
  - [The docs repo](https://github.com/kedacore/keda-docs)

Fixes #1402

### CODE REVIEW

File: interceptor/main_test.go [hunk 1]
```diff
@@ -152,7 +152,7 @@ func TestRunProxyServerCountMiddleware(t *testing.T) {
 	case hostAndCount := <-q.ResizedCh:
 		r.Equal(namespacedName, hostAndCount.Host)
 		r.Equal(1, hostAndCount.Count)
-	case <-time.After(4 * time.Second):
+	case <-time.After(5 * time.Second):
```
Comment (wozniakjan) [inline interceptor/main_test.go]: unit tests were flaking here too frequently
```
--- FAIL: TestRunProxyServerCountMiddleware (4.60s)
    main_test.go:156: 
        	Error Trace:	/__w/http-add-on/http-add-on/interceptor/main_test.go:156
        	Error:      	timeout waiting for -1 queue resize
        	Test:       	TestRunProxyServerCountMiddleware
--- FAIL: TestRunProxyServerWithTLSCountMiddleware (4.60s)
    main_test.go:306: 
        	Error Trace:	/__w/http-add-on/http-add-on/interceptor/main_test.go:306
        	Error:      	timeout waiting for -1 queue resize
        	Test:       	TestRunProxyServerWithTLSCountMiddleware
Running Suite: Interceptor Suite - /__w/http-add-on/http-add-on/interceptor
===========================================================================
```

likely related to https://github.com/kedacore/http-add-on/pull/1387, the timeout was bumped from 2s to 4s which was passing nicely yesterday but today results in highly flaky behavior. Bumping to 5s, will see if that is enough or if test refactor is needed :)
